export enum ESetterActionTypeKeys {
    SET_CLIENT_INFO = 'SET_CLIENT_INFO',
    SET_TABLE_POSITION = 'SET_TABLE_POSITION',
    SET_GAME_STATE = 'SET_GAME_STATE',
    SET_GRABBED_ENTITY_ORIGINAL_POSITION = 'SET_GRABBED_ENTITY_ORIGINAL_POSITION',
    SET_TABLE_CONNECTION_STATUS = 'SET_TABLE_CONNECTION_STATUS',
    SET_ORIENTATION = 'SET_ORIENTATION',
    SET_TABLE_READY = 'SET_TABLE_READY',
    SET_HORIZONTAL_SCALING_RATIO = 'SET_HORIZONTAL_SCALING_RATIO',
    SET_VERTICAL_SCALING_RATIO = 'SET_VERTICAL_SCALING_RATIO',
    SET_TABLE_VIRTUAL_DIMENSIONS = 'SET_TABLE_VIRTUAL_DIMENSIONS',
    SET_TABLE_PIXEL_DIMENSIONS = 'SET_TABLE_PIXEL_DIMENSIONS',
    SET_GRABBED_ENTITY_INFO = 'SET_GRABBED_ENTITY_INFO'
}

export enum ESocketActionTypeKeys {
    EMIT_VERB = 'socket/EMIT_VERB',
    CONNECT = 'socket/CONNECT',
    DISCONNECT = 'socket/DISCONNECT',
    JOIN_TABLE = 'socket/JOIN_TABLE',
}